----------------------------------------------------------------------------------------------------------
-- Copyright Todor Radonov 2022
-- Licnsed under Creative Commons CC BY-NC 4.0
-- https://creativecommons.org/licenses/by-nc/4.0/

function dummy()
	--do nothing
end
--==========X-Plane Datarefs==========--
--Electrical
bus_amp = find_dataref("sim/cockpit2/electrical/bus_load_amps[0]")
bus_amp2 = find_dataref("sim/cockpit2/electrical/bus_load_amps[1]")
bus_amp3 = find_dataref("sim/cockpit2/electrical/bus_load_amps[2]")
bus_volt = find_dataref("sim/cockpit2/electrical/bus_volts[0]") --duplicate
bus_volts = find_dataref("sim/cockpit2/electrical/bus_volts[0]") --duplicate
bat_volt =  find_dataref("sim/cockpit2/electrical/battery_voltage_indicated_volts[0]")
bus_load_add = find_dataref("sim/cockpit2/electrical/plugin_bus_load_amps[0]")
gen_off = find_dataref("sim/cockpit/warnings/annunciators/generator_off[0]")
ldg_lt = find_dataref("sim/cockpit2/switches/landing_lights_on")
taxi_lt = find_dataref("sim/cockpit2/switches/taxi_light_on")
nav_lt = find_dataref("sim/cockpit2/switches/navigation_lights_on")
strobe_lt = find_dataref("sim/cockpit2/switches/strobe_lights_on")
beacon_lt = find_dataref("sim/cockpit2/switches/beacon_on")
elec_hyd = find_dataref("sim/cockpit2/switches/electric_hydraulic_pump_on")
stat_heat = find_dataref("sim/cockpit/switches/static_heat_on")
inst_brt = find_dataref("sim/cockpit2/switches/instrument_brightness_ratio[0]")
wiper_speed = find_dataref("sim/cockpit2/switches/wiper_speed")
inverter_on = find_dataref("sim/cockpit2/electrical/inverter_on[0]")
starter_hit = find_dataref("sim/cockpit2/engine/actuators/starter_hit[0]")
com_pwr = find_dataref("sim/cockpit2/radios/actuators/com1_power")
nav_pwr = find_dataref("sim/cockpit2/radios/actuators/nav1_power")
com_brt = find_dataref("sim/cockpit2/switches/instrument_brightness_ratio[0]")
nav_brt = find_dataref("sim/cockpit2/switches/instrument_brightness_ratio[1]")
batt = find_dataref("sim/cockpit2/electrical/battery_on[0]")
gpu = find_dataref("sim/cockpit/electrical/gpu_on")
inst_light_fuse = find_dataref("custom/dromader/electrical/instruments_light")
static_heat = find_dataref("sim/cockpit/switches/static_heat_on")
--Engine
running_eng = find_dataref("sim/flightmodel/engine/ENGN_running[0]") --duplicate
engn_running = find_dataref("sim/flightmodel/engine/ENGN_running[0]") --duplicate
eng_running = find_dataref("sim/flightmodel/engine/ENGN_running[0]") --duplicate
starter_running = find_dataref("sim/flightmodel2/engines/starter_is_running[0]")
throttle_ratio = find_dataref("sim/flightmodel2/engines/throttle_used_ratio[0]")
engn_tacrad = find_dataref("sim/flightmodel/engine/ENGN_tacrad[0]")
fuel_burning = find_dataref("sim/flightmodel2/engines/engine_is_burning_fuel[0]")
fuel_flow_before_engine = find_dataref("sim/flightmodel2/engines/has_fuel_flow_before_mixture[0]")
fuel_flow = find_dataref("sim/flightmodel/engine/ENGN_FF_[0]")
max_throt = find_dataref("sim/aircraft/engine/acf_throtmax_FWD")
eng_cyl_temp = find_dataref("sim/flightmodel/engine/ENGN_CHT_c[0]")
eng_cyl_temp_max = find_dataref("sim/aircraft/engine/acf_max_CHT")
eng_egt = find_dataref("sim/flightmodel/engine/ENGN_EGT_c[0]")
eng_carb_temp = find_dataref("sim/cockpit2/engine/indicators/carburetor_temperature_C[0]")
eng_pwr = find_dataref("sim/flightmodel/engine/ENGN_power[0]") --duplicate
power_eng = find_dataref("sim/flightmodel/engine/ENGN_power[0]") --duplicate
eng_cyl_temp_red_lo = find_dataref("sim/aircraft/limits/red_lo_CHT")
eng_cyl_temp_red_hi = find_dataref("sim/aircraft/limits/red_hi_CHT")
eng_cyl_temp_green_lo = find_dataref("sim/aircraft/limits/green_lo_CHT")
eng_cyl_temp_green_hi = find_dataref("sim/aircraft/limits/green_hi_CHT")
eng_speed = find_dataref("sim/flightmodel/engine/ENGN_tacrad[0]")
eng_throt = find_dataref("sim/flightmodel/engine/ENGN_thro[0]")
eng_cowl = find_dataref("sim/flightmodel/engine/ENGN_cowl[0]")
eng_max_pwr_w = find_dataref("sim/aircraft2/engine/max_power_limited_watts")
MP_limit = find_dataref("sim/aircraft/limits/red_hi_MP")
MP_cur = find_dataref("sim/cockpit2/engine/indicators/MPR_in_hg[0]")
oil_flap = find_dataref("sim/flightmodel/engine/ENGN_cowl[1]")
oil_temp_max = find_dataref("sim/aircraft/engine/acf_max_OILT")
oil_temp = find_dataref("sim/flightmodel/engine/ENGN_oil_temp_c[0]")
oil_pres = find_dataref("sim/aircraft/engine/acf_max_OILP")
oil_press_lo_lim = find_dataref("sim/aircraft/limits/red_lo_oilP")
oil_press_hi_lim = find_dataref("sim/aircraft/limits/red_hi_oilP")
--Hydraulics
hyd_press_1 = find_dataref("sim/cockpit2/hydraulics/indicators/hydraulic_pressure_1")
hyd_press_2 = find_dataref("sim/cockpit2/hydraulics/indicators/hydraulic_pressure_2")
--Brakes
park_brake = find_dataref("sim/cockpit2/controls/parking_brake_ratio")
left_brake = find_dataref("sim/cockpit2/controls/left_brake_ratio")
right_brake = find_dataref("sim/cockpit2/controls/right_brake_ratio")
--Load
water_quantity = find_dataref("sim/flightmodel/weight/m_jettison")
water_quantity_max = find_dataref("sim/aircraft/weight/acf_m_jettison")
acf_weight = find_dataref("sim/flightmodel/weight/m_fixed")
--Audio
com_vol = find_dataref("sim/cockpit2/radios/actuators/audio_volume_com1")
gps_pwr = find_dataref("sim/cockpit2/radios/actuators/gps_power")
audio_com1 = find_dataref("sim/cockpit2/radios/actuators/audio_selection_com1")
audio_nav1 = find_dataref("sim/cockpit2/radios/actuators/audio_selection_nav1")
--Fuel
fuel_tank_selector = find_dataref("sim/cockpit2/fuel/fuel_tank_selector") -- (0=none,1=left,2=center,3=right,4=all)
fuel_press = find_dataref("sim/cockpit2/fuel/tank_pump_pressure_psi[0]")
ovveride_fuel = find_dataref("sim/operation/override/override_fuel_system")
fuel_quantity_left = find_dataref("sim/flightmodel/weight/m_fuel[0]")
fuel_quantity_right = find_dataref("sim/flightmodel/weight/m_fuel[1]")
--Failures
stall_fail = find_dataref("sim/operation/failures/rel_stall_warn")
starter_fail = find_dataref("sim/operation/failures/rel_startr0")
inst_light_fail = find_dataref("sim/operation/failures/rel_clights")
agk49_fail = find_dataref("sim/operation/failures/rel_invert0")
radio_fail = find_dataref("sim/operation/failures/rel_esys2")
transponder_fail = find_dataref("sim/operation/failures/rel_esys3")
eng_fail = find_dataref("sim/operation/failures/rel_engfai0")
eng_seize = find_dataref("sim/operation/failures/rel_seize_0")
eng_fire = find_dataref("sim/operation/failures/rel_engfir0")
smoke_cpit = find_dataref("sim/operation/failures/rel_smoke_cpit")
smoke_trail = find_dataref("sim/flightmodel/failures/smoking")
oil_fail = find_dataref("sim/operation/failures/rel_oilpmp0")
air_res = find_dataref("sim/operation/failures/rel_airres0")
door_detach_L = find_dataref("sim/operation/failures/rel_aftbur0")
door_detach_R = find_dataref("sim/operation/failures/rel_aftbur1")
pitot_fail = find_dataref("sim/operation/failures/rel_pitot")
ail_right_fail = find_dataref("sim/operation/failures/rel_fc_ail_R")
ail_left_fail = find_dataref("sim/operation/failures/rel_fc_ail_L")
elev_up_fail = find_dataref("sim/operation/failures/rel_fc_elv_U")
elev_down_fail = find_dataref("sim/operation/failures/rel_fc_elv_D")
rudder_L_fail = find_dataref("sim/operation/failures/rel_fc_rud_L")
rudder_R_fail = find_dataref("sim/operation/failures/rel_fc_rud_R")
elev_trim_fail = find_dataref("sim/operation/failures/rel_trim_elv")
ail_trim_fail = find_dataref("sim/operation/failures/rel_trim_ail")
rud_trim_fail = find_dataref("sim/operation/failures/rel_trim_rud")
--Control
joy_map = find_dataref("sim/joystick/joy_mapped_axis_avail") --starting from 0 - 9 mixture all eng, 28 mixture eng1, 29 mixture eng2.
joy_value = find_dataref("sim/joystick/joy_mapped_axis_value")
stick_roll = find_dataref("sim/joystick/yoke_roll_ratio")
stick_pitch = find_dataref("sim/joystick/yoke_pitch_ratio")
pedals_yaw = find_dataref("sim/joystick/yoke_heading_ratio")
--Propeller
prop_disc_ovrd = find_dataref("sim/flightmodel2/engines/prop_disc/override[0]")
prop_is_disc = find_dataref("sim/flightmodel2/engines/prop_is_disc[0]")
prop_rotation_angle_deg = find_dataref("sim/flightmodel2/engines/prop_rotation_angle_deg[0]")
prop_rotation_speed_rad_sec = find_dataref("sim/flightmodel2/engines/prop_rotation_speed_rad_sec[0]")
prop_pitch_deg = find_dataref("sim/flightmodel2/engines/prop_pitch_deg[0]")
disc_s_dim = find_dataref("sim/flightmodel2/engines/prop_disc/disc_s_dim[0]")
disc_t_dim = find_dataref("sim/flightmodel2/engines/prop_disc/disc_t_dim[0]")
disc_alpha_front = find_dataref("sim/flightmodel2/engines/prop_disc/disc_alpha_front[0]")
disc_alpha_side = find_dataref("sim/flightmodel2/engines/prop_disc/disc_alpha_side[0]")
disc_alpha_inside = find_dataref("sim/flightmodel2/engines/prop_disc/disc_alpha_inside[0]")
disc_width = find_dataref("sim/flightmodel2/engines/prop_disc/disc_width[0]")
side_width = find_dataref("sim/flightmodel2/engines/prop_disc/side_width[0]")
side_number_of_blades = find_dataref("sim/flightmodel2/engines/prop_disc/side_number_of_blades[0]")
side_s_dim = find_dataref("sim/flightmodel2/engines/prop_disc/side_s_dim[0]")
side_t_dim = find_dataref("sim/flightmodel2/engines/prop_disc/side_t_dim[0]")
side_alpha_front = find_dataref("sim/flightmodel2/engines/prop_disc/side_alpha_front[0]")
side_alpha_side = find_dataref("sim/flightmodel2/engines/prop_disc/side_alpha_side[0]")
side_alpha_inside = find_dataref("sim/flightmodel2/engines/prop_disc/side_alpha_inside[0]")
side_angle = find_dataref("sim/flightmodel2/engines/prop_disc/side_angle[0]")
side_is_billboard = find_dataref("sim/flightmodel2/engines/prop_disc/side_is_billboard[0]")
disc_s = find_dataref("sim/flightmodel2/engines/prop_disc/disc_s[0]")
disc_t = find_dataref("sim/flightmodel2/engines/prop_disc/disc_t[0]")
side_s = find_dataref("sim/flightmodel2/engines/prop_disc/side_s[0]")
side_t = find_dataref("sim/flightmodel2/engines/prop_disc/side_t[0]")
--Mixture
ovrd_mix = find_dataref("sim/operation/override/override_mixture")
mixture_eng = find_dataref("sim/flightmodel/engine/ENGN_mixt[0]")
--Misc
sim_time = find_dataref("sim/time/total_flight_time_sec")
startup_running = find_dataref("sim/operation/prefs/startup_running")
door5_ratio = find_dataref("sim/flightmodel2/misc/door_open_ratio[4]")
spd_dr = find_dataref("sim/flightmodel/position/groundspeed")
gspeed_mult = find_dataref("sim/time/ground_speed")
oat = find_dataref("sim/weather/temperature_ambient_c")
transp_code = find_dataref("sim/cockpit/radios/transponder_code")
transp_mode = find_dataref("sim/cockpit/radios/transponder_mode")
acf_cd = find_dataref("sim/aircraft/bodies/acf_fuse_cd")
air_speed = find_dataref("sim/flightmodel/forces/vz_air_on_acf")
prop_wash = find_dataref("sim/flightmodel2/engines/jetwash_mtr_sec[0]")
lat = find_dataref("sim/flightmodel/position/latitude")
lon = find_dataref("sim/flightmodel/position/longitude")
crs = find_dataref("sim/flightmodel/position/true_psi")
brt = find_dataref("sim/cockpit2/switches/instrument_brightness_ratio[4]")
alt_dr = find_dataref("sim/flightmodel/position/elevation")
hours = find_dataref("sim/cockpit2/clock_timer/local_time_hours")
minutes = find_dataref("sim/cockpit2/clock_timer/local_time_minutes")
hours_z = find_dataref("sim/cockpit2/clock_timer/zulu_time_hours")
minutes_z = find_dataref("sim/cockpit2/clock_timer/zulu_time_minutes")
seconds_z = find_dataref("sim/cockpit2/clock_timer/zulu_time_seconds")
day = find_dataref("sim/cockpit2/clock_timer/current_day")
month = find_dataref("sim/cockpit2/clock_timer/current_month")
draw_fires = find_dataref("sim/graphics/settings/draw_forestfires")
compass_heading = find_dataref("sim/cockpit2/gauges/indicators/compass_heading_deg_mag")
compass_g_side = find_dataref("sim/flightmodel/forces/g_side")
compass_g_nrml = find_dataref("sim/flightmodel/forces/g_nrml")
pilot_head_x = find_dataref("sim/graphics/view/pilots_head_x")
pilot_head_y = find_dataref("sim/graphics/view/pilots_head_y")
pilot_head_z = find_dataref("sim/graphics/view/pilots_head_z")
ext_view = find_dataref("sim/graphics/view/view_is_external")

--==========Custom Datarefs no callback==========--